"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useDeferredValue, useEffect, useMemo, useState, useTransition } from "react";
import { Activity, ArrowRight, BarChart3, Check, ChevronDown, CircleAlert, ExternalLink, FilePlus2, Gauge, LayoutDashboard, ListChecks, LogOut, Menu, MoreHorizontal, Plus, RefreshCw, Search, Settings, Sheet, SlidersHorizontal, Sparkles, X } from "lucide-react";
import type { ActionItem, ClaimObservation, CompetitorProfile, IntelligenceData, Platform, Source } from "@/types";

const nav = [
  { href:"/", label:"Today", icon:LayoutDashboard }, { href:"/competitors", label:"Competitors", icon:Search },
  { href:"/compare", label:"Compare", icon:BarChart3 }, { href:"/opportunities", label:"Opportunities", icon:Sparkles },
  { href:"/tracker", label:"Tracker", icon:ListChecks },
];
const profileTabs = ["Overview","Product & Features","GTM & Reach","Pricing","Sources"] as const;
type ProfileTab = typeof profileTabs[number];
type ModalState = { type:"source"|"note"|"action"; platform:Platform; opportunity?:IntelligenceData["recommendations"][number] } | null;

export default function DashboardClient({ initialData, section }: { initialData:IntelligenceData; section:string }) {
  const pathname=usePathname();
  const [data,setData]=useState(initialData); const [query,setQuery]=useState(""); const deferredQuery=useDeferredValue(query);
  const [side,setSide]=useState("All"); const [geography,setGeography]=useState("All"); const [evidence,setEvidence]=useState("All");
  const [menuOpen,setMenuOpen]=useState(false); const [selectedId,setSelectedId]=useState(initialData.platforms[0]?.id??"");
  const [modal,setModal]=useState<ModalState>(null); const [notice,setNotice]=useState(""); const [isPending,startTransition]=useTransition();

  const profileMap=useMemo(()=>new Map(data.profiles.map((profile)=>[profile.platformId,profile])),[data.profiles]);
  const aliasMap=useMemo(()=>new Map(data.aliases.map((alias)=>[alias.platformId,(alias.alias??"").toLowerCase()])),[data.aliases]);
  const filtered=useMemo(()=>data.platforms.filter((platform)=>{
    const profile=profileMap.get(platform.id); const haystack=[platform.name,aliasMap.get(platform.id),platform.category,platform.geography,platform.side,profile?.productSummary,profile?.featuresSummary,profile?.usp,profile?.acquisitionStrategy,profile?.reachSummary,profile?.importantLinks].join(" ").toLowerCase();
    return (!deferredQuery||haystack.includes(deferredQuery.toLowerCase()))&&(side==="All"||platform.side===side)&&(geography==="All"||platform.geography===geography)&&(evidence==="All"||platform.evidenceStatus===evidence);
  }),[data.platforms,profileMap,aliasMap,deferredQuery,side,geography,evidence]);

  useEffect(()=>{ if(data.meta.mode!=="google-sheets")return; const timer=window.setInterval(async()=>{try{const response=await fetch("/api/sync/revision",{cache:"no-store"});if(!response.ok)return;const sync=await response.json();if(sync.revision!==data.meta.datasetRevision){const next=await fetch(`/api/data?section=${section}`,{cache:"no-store"});if(next.ok)setData(await next.json());}}catch{}},30000);return()=>window.clearInterval(timer);},[data.meta.datasetRevision,data.meta.mode,section]);

  const refresh=()=>startTransition(async()=>{setNotice("Refreshing live research…");try{const response=await fetch(`/api/data?section=${section}`,{cache:"no-store"});if(!response.ok)throw new Error((await response.json()).error||"Refresh failed");setData(await response.json());setNotice("Research refreshed");}catch(error){setNotice(error instanceof Error?error.message:"Refresh failed");}});
  const loadPlatform=(id:string)=>startTransition(async()=>{if(!id||data.claims.some((row)=>row.platformId===id))return;try{const response=await fetch(`/api/platforms/${id}`,{cache:"no-store"});if(!response.ok)throw new Error("Profile detail unavailable");const detail=await response.json();setData((current)=>{const without=(rows:Array<{platformId:string}>)=>rows.filter((row)=>row.platformId!==id);const sources=[...current.sources,...detail.sources.filter((source:Source)=>!current.sources.some((row)=>row.id===source.id))];return {...current,claims:[...without(current.claims),...detail.claims],modules:[...without(current.modules),...detail.modules],featureObservations:[...without(current.featureObservations),...detail.features],pricing:[...without(current.pricing),...detail.pricing],reachMetrics:[...without(current.reachMetrics),...detail.metrics],gtmObservations:[...without(current.gtmObservations),...detail.gtm],notes:[...without(current.notes),...detail.notes],sources};});}catch(error){setNotice(error instanceof Error?error.message:"Profile detail unavailable");}});
  const selectPlatform=(id:string)=>{setSelectedId(id);loadPlatform(id);};
  const title=section==="today"?"Today":section[0].toUpperCase()+section.slice(1);
  const effectiveSelectedId=filtered.some((row)=>row.id===selectedId)?selectedId:(filtered[0]?.id??"");
  return <div className="app-shell">
    <aside className={`sidebar ${menuOpen?"open":""}`}>
      <Link className="brand" href="/" onClick={()=>setMenuOpen(false)}>HireNudge</Link>
      <div className="workspace-label">INTELLIGENCE</div>
      <nav>{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} className={pathname===href?"active":""} onClick={()=>setMenuOpen(false)}><Icon size={18}/><span>{label}</span></Link>)}</nav>
      <div className="sidebar-footer"><Link href="/settings" className={pathname==="/settings"?"active":""}><Settings size={18}/>Settings</Link><form action="/api/auth/logout" method="post"><button type="submit"><LogOut size={17}/>Log out</button></form><small>Private Founder’s Office workspace</small></div>
    </aside>
    {menuOpen?<button className="nav-scrim" aria-label="Close navigation" onClick={()=>setMenuOpen(false)}/>:null}
    <main className="main-area">
      <header className="topbar">
        <button className="mobile-menu" onClick={()=>setMenuOpen(true)} aria-label="Open navigation"><Menu size={22}/></button>
        <div className="page-title"><h1>{title}</h1><p>{filtered.length} of {data.platforms.length} competitors</p></div>
        <label className="global-search"><Search size={18}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search companies, features, GTM, sources…" aria-label="Search intelligence"/>{query?<button onClick={()=>setQuery("")} aria-label="Clear search"><X size={16}/></button>:null}</label>
        <Filter label="Side" value={side} onChange={setSide} values={["All",...unique(data.platforms.map((row)=>row.side))]}/>
        <Filter label="Geography" value={geography} onChange={setGeography} values={["All",...unique(data.platforms.map((row)=>row.geography))]}/>
        <Filter label="Evidence" value={evidence} onChange={setEvidence} values={["All",...unique(data.platforms.map((row)=>row.evidenceStatus))]}/>
        <a className="sheet-button" href={data.meta.sheetUrl} target="_blank" rel="noreferrer"><Sheet size={17}/>Open Google Sheet</a>
        <button className="icon-button" onClick={refresh} aria-label="Refresh live data" disabled={isPending}><RefreshCw size={18}/></button>
      </header>
      {notice?<button className="notice" onClick={()=>setNotice("")}>{notice}<X size={15}/></button>:null}
      {data.meta.mode==="unavailable"?<UnavailableState data={data} onRefresh={refresh}/>:section==="today"?<TodayView data={data} onCreateAction={(platform)=>setModal({type:"action",platform})}/>:section==="competitors"?<CompetitorsView data={data} platforms={filtered} selectedId={effectiveSelectedId} onSelect={selectPlatform} onModal={setModal}/>:section==="compare"?<CompareView data={data} visiblePlatforms={filtered} onLoad={loadPlatform}/>:section==="opportunities"?<OpportunitiesView data={data} query={deferredQuery} onCreate={(opportunity)=>setModal({type:"action",platform:data.platforms[0],opportunity})}/>:section==="tracker"?<TrackerWorkspace data={data} setData={setData} setNotice={setNotice}/>:<SettingsView data={data} onRefresh={refresh}/>} 
    </main>
    {modal?<EditorModal state={modal} onClose={()=>setModal(null)} onSaved={(message)=>{setModal(null);setNotice(message);refresh();}}/>:null}
  </div>;
}

function Filter({label,value,onChange,values}:{label:string;value:string;onChange:(value:string)=>void;values:string[]}){return <label className="filter-control"><span>{label}</span><span className="select-wrap"><select value={value} onChange={(event)=>onChange(event.target.value)}>{values.map((item)=><option key={item}>{item}</option>)}</select><ChevronDown size={14}/></span></label>}
function unique(values:string[]){return Array.from(new Set(values.filter(Boolean))).sort();}

function TodayView({data,onCreateAction}:{data:IntelligenceData;onCreateAction:(platform:Platform)=>void}){
  const [now]=useState(()=>Date.now());
  const attention=data.completion.filter((row)=>row.status!=="Green").length;
  const due=data.actions.filter((row)=>row.dueDate&&new Date(row.dueDate).getTime()<now&&!/done|rejected|deferred/i.test(row.status)).length;
  const sevenDaysAgo=now-7*86400000; const recent=data.news.filter((item)=>new Date(item.publicationDate||item.eventDate).getTime()>=sevenDaysAgo&&item.status!=="Archived").sort((a,b)=>new Date(b.eventDate).getTime()-new Date(a.eventDate).getTime()).slice(0,25); const priorities=data.recommendations.slice().sort((a,b)=>b.score-a.score).slice(0,4);
  return <div className="today-page"><section className="today-hero"><div><h2>Competitive decisions, not dashboard noise.</h2><p>Review what changed, validate the strongest transfer ideas, and move one bounded experiment forward.</p></div><Link className="primary-button" href="/competitors">Review competitors <ArrowRight size={17}/></Link></section>
    <div className="health-strip"><Metric value={data.meta.coreCount} label="Core competitors" detail="Terminal fields do not imply verification"/><Metric value={data.meta.watchlistCount} label="Emerging watchlist" detail="Source-backed startup radar"/><Metric value={attention} label="Quality gates open" detail="Staging stays private until green" tone={attention?"amber":"green"}/><Metric value={due} label="Overdue actions" detail="Priyansh + Baskaran co-own by default" tone={due?"red":"green"}/></div>
    <div className="today-columns"><section className="section-block"><SectionTitle title="Priority decisions" meta="Highest opportunity score; trust risk remains separate" link="/opportunities"/>{priorities.map((item)=><article className="decision-row" key={item.id}><div className="score">{item.score.toFixed(1)}</div><div><strong>{item.name}</strong><p>{item.rationale}</p><span>{item.recommendation} · {item.priority} · Evidence {item.evidenceConfidence}</span></div><button onClick={()=>onCreateAction(data.platforms[0])}>Create action</button></article>)}</section>
      <section className="section-block watch-week"><SectionTitle title="Watch this week" meta={`${recent.length} source-backed items from the last seven days`} link="/opportunities"/>{recent.length?recent.map((item)=><article className="signal-row" key={item.id}><span>{item.signalType} · {item.geography} · {item.eventDate}</span><a href={item.sourceUrl} target="_blank" rel="noreferrer"><strong>{item.headline}</strong><ExternalLink size={13}/></a><p>{item.extractedFact}</p><small>{item.whyItMatters}</small></article>):<Empty title="No current signals passed the evidence policy" body="The feed excludes stale, duplicate and unsourced items."/>}</section></div>
  </div>;
}
function Metric({value,label,detail,tone="blue"}:{value:number;label:string;detail:string;tone?:string}){return <div className={`metric ${tone}`}><strong>{value}</strong><div><span>{label}</span><small>{detail}</small></div></div>}
function SectionTitle({title,meta,link}:{title:string;meta:string;link:string}){return <div className="section-title"><div><h3>{title}</h3><p>{meta}</p></div><Link href={link}>View all <ArrowRight size={15}/></Link></div>}

function CompetitorsView({data,platforms,selectedId,onSelect,onModal}:{data:IntelligenceData;platforms:Platform[];selectedId:string;onSelect:(id:string)=>void;onModal:(state:ModalState)=>void}){
  const selected=data.platforms.find((row)=>row.id===selectedId)??platforms[0]; const [tab,setTab]=useState<ProfileTab>("Overview"); const [menu,setMenu]=useState(false);
  if(!selected)return <Empty title="No competitors match" body="Clear filters or reconnect the live Google Sheet."/>;
  const profile=data.profiles.find((row)=>row.platformId===selected.id); const slugName=selected.name.toLowerCase().replace(/[^a-z0-9]/g,"");
  const sourceIds=new Set([...data.featureObservations.filter((row)=>row.platformId===selected.id).flatMap((row)=>row.sourceIds?.length?row.sourceIds:[row.sourceId]),...data.pricing.filter((row)=>row.platformId===selected.id).map((row)=>row.sourceId),...data.gtmObservations.filter((row)=>row.platformId===selected.id).map((row)=>row.sourceId),...data.reachMetrics.filter((row)=>row.platformId===selected.id).map((row)=>row.sourceId),...data.claims.filter((row)=>row.platformId===selected.id).flatMap((row)=>row.sourceIds)]);
  const sources=data.sources.filter((source)=>sourceIds.has(source.id)||source.id.toLowerCase().includes(slugName)||host(source.url)===host(selected.website));
  return <div className="competitor-workbench"><section className="competitor-list"><div className="list-heading"><h2>Competitors</h2><span>{platforms.length}</span></div><div className="list-scroll">{platforms.map((platform)=>{const completion=data.completion.find((row)=>row.platformId===platform.id);return <button key={platform.id} className={platform.id===selected.id?"selected":""} onClick={()=>onSelect(platform.id)}><Mark name={platform.name}/><div><strong>{platform.name}</strong><span>{platform.category}</span><small>{completion?`${completion.completionPercentage}% terminal · ${completion.status} · ${completion.freshness}`:`Research gate not calculated`} · {platform.geography}</small></div><i className={completion?.status==="Green"?"green":"amber"}/></button>})}</div></section>
    <section className="profile-view"><header className="profile-header"><Mark name={selected.name} large/><div><h2>{selected.name}</h2><p>{selected.category} · {selected.geography}</p></div><a className="secondary-button" href={selected.website} target="_blank" rel="noreferrer">Website <ExternalLink size={15}/></a><button className="secondary-button" onClick={()=>onModal({type:"source",platform:selected})}><FilePlus2 size={16}/>Add source</button><div className="menu-wrap"><button className="icon-button" aria-label="Profile actions" onClick={()=>setMenu((value)=>!value)}><MoreHorizontal size={19}/></button>{menu?<div className="overflow-menu"><button onClick={()=>{setMenu(false);onModal({type:"note",platform:selected})}}>Add research note</button><button onClick={()=>{setMenu(false);onModal({type:"action",platform:selected})}}>Create linked action</button></div>:null}</div></header>
      <div className="profile-tabs" role="tablist">{profileTabs.map((name)=><button key={name} role="tab" aria-selected={tab===name} className={tab===name?"active":""} onClick={()=>setTab(name)}>{name}</button>)}</div>
      <ProfileContent tab={tab} platform={selected} profile={profile} data={data} sources={sources} onModal={onModal}/>
    </section></div>;
}

function ProfileContent({tab,platform,profile,data,sources,onModal}:{tab:ProfileTab;platform:Platform;profile?:CompetitorProfile;data:IntelligenceData;sources:Source[];onModal:(state:ModalState)=>void}){
  const observations=data.featureObservations.filter((row)=>row.platformId===platform.id); const featureById=new Map(data.features.map((feature)=>[feature.id,feature.name])); const pricing=data.pricing.filter((row)=>row.platformId===platform.id&&row.platform!=="HireNudge"); const metrics=data.reachMetrics.filter((row)=>row.platformId===platform.id); const gtm=data.gtmObservations.filter((row)=>row.platformId===platform.id); const notes=data.notes.filter((row)=>row.platformId===platform.id); const claims=data.claims.filter((row)=>row.platformId===platform.id&&row.current); const claimByField=new Map(claims.map((claim)=>[claim.fieldKey,claim])); const sourceById=new Map(data.sources.map((source)=>[source.id,source])); const completion=data.completion.find((row)=>row.platformId===platform.id);
  const claim=(field:string)=>claimByField.get(field); const value=(field:string,fallback?:string)=>terminalText(claim(field)?.value||fallback);
  if(tab==="Product & Features")return <div className="profile-content"><div className="editorial-block"><h3>Product workflow</h3><EvidenceRichText value={value("jobs_to_be_done",profile?.productSummary)} claim={claim("jobs_to_be_done")} sourceById={sourceById}/></div><div className="feature-list">{observations.length?observations.map((item)=><div key={item.id} className={item.availability==="No"?"not-observed":""}>{item.availability==="No"?<CircleAlert size={17}/>:<Check size={17}/>}<span><strong>{featureById.get(item.featureId)||item.featureId.replace(/^feature-/,"").replace(/-/g," ")}</strong><small>{item.availability} · depth {item.depth} · {item.researchState||item.evidenceStatus} · {item.observedDate}</small><EvidenceLinks ids={item.sourceIds?.length?item.sourceIds:[item.sourceId]} sourceById={sourceById}/></span></div>):<TerminalState text="No material product module was found across accessible official product, pricing, help and documentation sources."/>}</div></div>;
  if(tab==="GTM & Reach")return <div className="profile-content two-column"><div><h3>Positioning & acquisition</h3><EvidenceFact label="Positioning" value={value("positioning",profile?.productSummary)} claim={claim("positioning")} sourceById={sourceById}/><EvidenceFact label="USP" value={value("usp",profile?.usp)} claim={claim("usp")} sourceById={sourceById}/><EvidenceFact label="Acquisition strategy" value={value("gtm",profile?.acquisitionStrategy)} claim={claim("gtm")} sourceById={sourceById}/>{gtm.map((item)=><Fact key={item.id} label={item.channel} value={item.strategy}/>)}</div><div><h3>Observable reach</h3>{metrics.length?metrics.map((item)=><div className="reach-row" key={item.id}><span>{item.channel}</span><strong>{terminalText(item.valueLabel)}</strong><small>{item.evidenceStatus} · {item.observedDate}</small><EvidenceLinks ids={[item.sourceId]} sourceById={sourceById}/></div>):<EvidenceRichText value={value("observable_reach","Not found after exhaustive search")} claim={claim("observable_reach")} sourceById={sourceById}/>}</div></div>;
  if(tab==="Pricing")return <div className="profile-content"><h3>Public pricing</h3>{pricing.length?<div className="data-table pricing"><strong>Tier</strong><strong>Billing</strong><strong>Price</strong><strong>Monthly</strong><strong>Limits</strong>{pricing.map((item)=><div className="table-row" key={item.id}><span>{item.tier}</span><span>{item.billingPeriod}</span><span>{item.nativePrice==null?terminalText(item.pricingStatus):`${item.currency} ${item.nativePrice}`}</span><span>{item.monthlyEquivalent==null?"—":`${item.currency} ${item.monthlyEquivalent.toFixed(2)}`}</span><span>{item.limits}<EvidenceLinks ids={[item.sourceId]} sourceById={sourceById}/></span></div>)}</div>:<EvidenceRichText value={value("pricing","Not publicly disclosed")} claim={claim("pricing")} sourceById={sourceById}/>}<p className="method-note">HireNudge tiers are excluded from competitor profiles and appear only when explicitly selected in Compare. “Not publicly disclosed” is not treated as free or zero.</p></div>;
  if(tab==="Sources")return <div className="profile-content"><div className="content-heading"><div><h3>Evidence ledger</h3><p>Material claims carry a terminal evidence state, observation date and source lineage.</p></div><button className="primary-button" onClick={()=>onModal({type:"source",platform})}><Plus size={16}/>Add source</button></div>{sources.length?<div className="source-list">{sources.map((source)=><article key={source.id}><Activity size={18}/><div><a href={source.url} target="_blank" rel="noreferrer">{source.title||source.url}</a><span>{source.type} · Observed {source.observedDate||"date not published"}</span></div><em>{terminalText(source.status)}</em></article>)}</div>:<TerminalState text="No linked public source was found after exhaustive search; the source check remains recorded in the research ledger."/>}{notes.length?<div className="notes-section"><h3>Research notes</h3>{notes.map((note)=><article key={note.id}><strong>{note.title}</strong><p>{note.body}</p><small>{note.createdBy} · {note.createdAt}</small></article>)}</div>:null}</div>;
  return <div className="profile-content overview-grid"><div className="overview-main"><div className="editorial-block"><h3>What they do</h3><EvidenceRichText value={value("jobs_to_be_done",profile?.productSummary)} claim={claim("jobs_to_be_done")} sourceById={sourceById}/></div><div className="editorial-columns"><div><h3>Why they win</h3><EvidenceRichText value={value("strengths",profile?.whyTheyWin)} claim={claim("strengths")} sourceById={sourceById}/></div><div><h3>Weakness / unresolved problem</h3><EvidenceRichText value={value("weaknesses",profile?.weaknesses)} claim={claim("weaknesses")} sourceById={sourceById}/></div></div><div className="editorial-block implication"><h3>HireNudge implication</h3><EvidenceRichText value={value("hirenudge_recommendation",profile?.hirenudgeImplication)} claim={claim("hirenudge_recommendation")} sourceById={sourceById}/></div><div className="editorial-columns trust-review"><div><h3>Trust & privacy</h3><EvidenceRichText value={value("trust",profile?.trustSummary)} claim={claim("trust")} sourceById={sourceById}/></div><div><h3>Review themes</h3><EvidenceRichText value={value("review_themes",profile?.reviewThemes)} claim={claim("review_themes")} sourceById={sourceById}/></div></div></div><aside className="profile-aside"><Fact label="Founder" value={profile?.founder||"Not publicly disclosed"} link={profile?.founderUrl}/><EvidenceFact label="Location" value={value("headquarters",profile?.location)} claim={claim("headquarters")} sourceById={sourceById}/><EvidenceFact label="Reach" value={value("observable_reach",profile?.reachSummary)} claim={claim("observable_reach")} sourceById={sourceById}/><EvidenceFact label="Revenue" value={value("revenue_status",profile?.revenueStatus)} claim={claim("revenue_status")} sourceById={sourceById}/><Fact label="Research gate" value={completion?`${completion.status} · ${completion.completionPercentage}% terminal fields`:"Research gate not calculated"}/><Fact label="Freshness" value={completion?.freshness||profile?.freshness||"Observation date not recorded"}/><Fact label="Source coverage" value={completion?`${completion.sourceCoveragePercentage}% · ${sources.length} linked sources`:`${sources.length} linked source${sources.length===1?"":"s"}`}/></aside></div>;
}

function CompareView({data,visiblePlatforms,onLoad}:{data:IntelligenceData;visiblePlatforms:Platform[];onLoad:(id:string)=>void}){
  const defaults=data.platforms.filter((row)=>row.side==="Candidate-side").slice(0,4).map((row)=>row.id); const [selected,setSelected]=useState<string[]>(defaults);
  const setAt=(index:number,value:string)=>{setSelected((current)=>current.map((item,i)=>i===index?value:item));if(value!=="platform-hirenudge")onLoad(value);}; const hireNudge:Platform={id:"platform-hirenudge",name:"HireNudge",category:"Job-search operating system",geography:"India",website:"https://hirenudge.ai/",side:"Candidate-side",lifecycle:"Internal product",evidenceStatus:"Internal validation pending",sourceFreshness:"Internal",classificationSource:"HireNudge workspace",reviewDue:"",rowVersion:1}; const selectedPlatforms=selected.map((id)=>id===hireNudge.id?hireNudge:data.platforms.find((row)=>row.id===id)).filter(Boolean) as Platform[];
  const lookup=new Map(data.featureObservations.map((item)=>[`${item.platformId}:${item.featureId}`,item]));
  return <div className="route-page"><div className="route-heading"><div><h2>Compare up to four platforms</h2><p>Each cell shows an observation or an explicit terminal evidence state; missing data is never converted to No or zero.</p></div></div><div className="compare-selectors">{[0,1,2,3].map((index)=><label key={index}><span>Platform {index+1}</span><select value={selected[index]||""} onChange={(event)=>setAt(index,event.target.value)}><option value="">None</option>{visiblePlatforms.map((platform)=><option key={platform.id} value={platform.id} disabled={selected.some((id,i)=>i!==index&&id===platform.id)}>{platform.name}</option>)}{!visiblePlatforms.some((p)=>p.name==="HireNudge")?<option value="platform-hirenudge">HireNudge</option>:null}</select></label>)}</div>
    <div className="comparison-table"><div className="compare-head"><strong>Feature</strong>{selectedPlatforms.map((platform)=><strong key={platform.id}>{platform.name}</strong>)}</div>{data.features.map((feature)=><div className="compare-row" key={feature.id}><span>{feature.name}</span>{selectedPlatforms.map((platform)=>{const item=lookup.get(`${platform.id}:${feature.id}`);return <span key={platform.id} className={item&&item.availability!=="No"?"available":"unknown"}>{item?`${item.availability} · depth ${item.depth} · ${terminalText(item.researchState||item.evidenceStatus)}`:"Not found after exhaustive search"}</span>})}</div>)}</div>
    <section className="compare-pricing"><h3>Pricing tiers</h3>{selectedPlatforms.map((platform)=><div key={platform.id}><h4>{platform.name}</h4>{data.pricing.filter((row)=>row.platformId===platform.id).length?data.pricing.filter((row)=>row.platformId===platform.id).map((tier)=><span key={tier.id}>{tier.tier}: {tier.nativePrice==null?terminalText(tier.pricingStatus):`${tier.currency} ${tier.nativePrice}`} · {tier.billingPeriod}</span>):<span>{terminalText(data.claims.find((claim)=>claim.platformId===platform.id&&claim.fieldKey==="pricing"&&claim.current)?.value||"Not publicly disclosed")}</span>}</div>)}</section></div>;
}

function OpportunitiesView({data,query,onCreate}:{data:IntelligenceData;query:string;onCreate:(item:IntelligenceData["recommendations"][number])=>void}){
  const [view,setView]=useState<"recommendations"|"watchlist"|"news">("recommendations"); const recommendations=data.recommendations.filter((item)=>`${item.name} ${item.rationale} ${item.recommendation}`.toLowerCase().includes(query.toLowerCase())); const discoveries=data.discoveries.filter((item)=>`${String(item.name)} ${String(item.signal)} ${String(item.sourceFamily)}`.toLowerCase().includes(query.toLowerCase())); const news=data.news.filter((item)=>`${item.headline} ${item.company} ${item.extractedFact} ${item.whyItMatters}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="route-page"><div className="route-heading"><div><h2>Opportunities & market radar</h2><p>Turn competitor learning into a decision, experiment, owner, metric, and deadline.</p></div><div className="segmented"><button className={view==="recommendations"?"active":""} onClick={()=>setView("recommendations")}>Recommendations</button><button className={view==="news"?"active":""} onClick={()=>setView("news")}>News</button><button className={view==="watchlist"?"active":""} onClick={()=>setView("watchlist")}>Watchlist</button></div></div>{view==="recommendations"?<div className="opportunity-list">{recommendations.map((item)=><article key={item.id}><div className="score large">{item.score.toFixed(1)}</div><div><div className="eyeline"><span>{item.recommendation}</span><em>{item.priority}</em></div><h3>{item.name}</h3><p>{item.rationale}</p><small>Evidence {item.evidenceConfidence} · Feasibility {item.feasibility}/5 · Privacy risk {item.privacyRisk}</small></div><button className="primary-button" onClick={()=>onCreate(item)}>Create action</button></article>)}</div>:view==="news"?<div className="news-archive">{news.map((item)=><article key={item.id}><div className="eyeline"><span>{item.signalType}</span><em>{item.eventDate}</em></div><a href={item.sourceUrl} target="_blank" rel="noreferrer"><h3>{item.headline}</h3><ExternalLink size={14}/></a><p>{item.extractedFact}</p><strong>Why it matters</strong><p>{item.whyItMatters}</p><small>{item.researchState} · {item.confidence} confidence · {item.sourceType}</small></article>)}</div>:<div className="watch-table"><strong>Company</strong><strong>Source</strong><strong>Why it matters</strong><strong>Status</strong><strong>Risk</strong>{discoveries.map((item)=><div className="table-row" key={String(item.id)}><span>{String(item.name)}</span><span>{String(item.sourceFamily)}</span><span>{String(item.signal)}</span><span>{terminalText(String(item.status))}</span><span>{String(item.risk)}</span></div>)}</div>}</div>;
}

function TrackerWorkspace({data,setData,setNotice}:{data:IntelligenceData;setData:(data:IntelligenceData)=>void;setNotice:(message:string)=>void}){
  const [view,setView]=useState<"table"|"board">("table");
  const [selectedId,setSelectedId]=useState("");
  const selected=data.actions.find((item)=>item.id===selectedId);
  const columns=["Proposed","Discussing","Approved","Planned","In progress","Validating","Done"];
  return <div className="tracker-workspace">
    <div className="tracker-toolbar">
      <div className="segmented"><button className={view==="table"?"active":""} onClick={()=>setView("table")}>Table</button><button className={view==="board"?"active":""} onClick={()=>setView("board")}>Board</button></div>
      <label><span>Open action detail</span><select value={selectedId} onChange={(event)=>setSelectedId(event.target.value)}><option value="">Select an action</option>{data.actions.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label>
    </div>
    {view==="table"?<TrackerView data={data} setData={setData} setNotice={setNotice}/>:<div className="tracker-board">{columns.map((status)=><section key={status}><header><strong>{status}</strong><span>{data.actions.filter((item)=>item.status===status).length}</span></header>{data.actions.filter((item)=>item.status===status).map((item)=><button key={item.id} onClick={()=>setSelectedId(item.id)}><small>{item.actionType||item.recommendationType} · {item.priority}</small><strong>{item.title}</strong><span>{item.owner||"Priyansh; Baskaran"}</span><em>{item.dueDate||"No due date"}</em></button>)}</section>)}</div>}
    {selected?<ActionDetail action={selected} data={data} setData={setData} onClose={()=>setSelectedId("")} setNotice={setNotice}/>:null}
  </div>;
}

function ActionDetail({action,data,setData,onClose,setNotice}:{action:ActionItem;data:IntelligenceData;setData:(data:IntelligenceData)=>void;onClose:()=>void;setNotice:(message:string)=>void}){
  const [saving,setSaving]=useState(false);
  const comments=data.actionComments.filter((comment)=>comment.actionId===action.id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{
    event.preventDefault(); setSaving(true);
    const values=Object.fromEntries(new FormData(event.currentTarget).entries());
    const response=await fetch(`/api/actions/${action.id}/comments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body:values.body,author:values.author,commentType:values.commentType,decision:values.decision||"",sourceSnapshotId:action.origin?.entityId||action.sourceId||""})});
    const result=await response.json(); setSaving(false);
    if(!response.ok){setNotice(result.error||"Comment could not be saved");return;}
    setData({...data,actionComments:[...data.actionComments,result.comment]}); setNotice("Discussion saved to Google Sheets"); event.currentTarget.reset();
  };
  return <div className="action-detail-backdrop" role="presentation" onMouseDown={(event)=>event.target===event.currentTarget&&onClose()}><aside className="action-detail" role="dialog" aria-modal="true" aria-labelledby="action-detail-title"><header><div><span>{action.actionType||action.recommendationType} · {action.status}</span><h2 id="action-detail-title">{action.title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close action detail"><X size={19}/></button></header><div className="action-detail-body"><dl><div><dt>Co-owners</dt><dd>{action.owner||"Priyansh; Baskaran"}</dd></div><div><dt>Outcome</dt><dd>{action.intendedOutcome}</dd></div><div><dt>Experiment</dt><dd>{action.experiment}</dd></div><div><dt>Success metric</dt><dd>{action.successMetric}</dd></div><div><dt>Evidence snapshot</dt><dd>{action.origin?.snapshot||action.customerProblem}</dd></div></dl><section className="discussion"><h3>Founder’s Office discussion</h3>{comments.length?comments.map((comment)=><article key={comment.id}><div><strong>{comment.author}</strong><span>{comment.commentType} · {comment.createdAt}</span></div><p>{comment.body}</p>{comment.decision?<em>{comment.decision}</em>:null}</article>):<p className="terminal">No discussion has been recorded for this action.</p>}<form onSubmit={submit}><div className="form-grid"><SelectField label="Author" name="author" values={["Founder’s Office","Priyansh","Baskaran","Divyansh"]}/><SelectField label="Type" name="commentType" values={["Comment","Question","Decision","Evidence"]}/></div><TextArea label="Comment" name="body" required/><Field label="Decision or next step (optional)" name="decision"/><button className="primary-button" disabled={saving}>{saving?"Saving…":"Add to discussion"}</button></form></section></div></aside></div>;
}

function TrackerView({data,setData,setNotice}:{data:IntelligenceData;setData:(data:IntelligenceData)=>void;setNotice:(message:string)=>void}){
  const update=async(item:ActionItem,field:keyof ActionItem,value:string)=>{const optimistic=data.actions.map((row)=>row.id===item.id?{...row,[field]:value}:row);setData({...data,actions:optimistic});const response=await fetch(`/api/tracker/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({rowVersion:item.rowVersion,changes:{[field]:value}})});const result=await response.json();if(response.ok){setData({...data,actions:data.actions.map((row)=>row.id===item.id?result.action:row)});setNotice("Tracker saved to Google Sheets");}else if(response.status===409){setData({...data,actions:data.actions.map((row)=>row.id===item.id?result.current:row)});setNotice(`Version conflict: ${item.title} changed in the Sheet. Current values restored.`);}else{setData(data);setNotice(result.error||"Write failed; change was not applied.");}};
  return <div className="route-page"><div className="route-heading"><div><h2>Action & experiment tracker</h2><p>Two-way tracker. Priyansh and Baskaran co-own new actions; updates are version checked by immutable ID.</p></div><span className={`connection ${data.meta.mode}`}>{data.meta.mode==="google-sheets"?"Live Google Sheets":"Connector unavailable"}</span></div><div className="tracker-table"><strong>Action</strong><strong>Co-owners</strong><strong>Priority</strong><strong>Due</strong><strong>Status</strong><strong>Success metric</strong>{data.actions.map((item)=><div className="table-row" key={item.id}><div><b>{item.title}</b><small>{item.actionType||item.recommendationType} · v{item.rowVersion}</small></div><input key={`${item.id}-${item.rowVersion}-owner`} defaultValue={item.owner||"Priyansh; Baskaran"} onBlur={(event)=>event.target.value!==item.owner&&update(item,"owner",event.target.value)}/><select value={item.priority} onChange={(event)=>update(item,"priority",event.target.value)}><option>P0</option><option>P1</option><option>P2</option><option>P3</option></select><input type="date" value={item.dueDate} onChange={(event)=>update(item,"dueDate",event.target.value)}/><select value={item.status} onChange={(event)=>update(item,"status",event.target.value)}>{["Proposed","Discussing","Approved","Planned","In progress","Validating","Done","Rejected","Deferred"].map((status)=><option key={status}>{status}</option>)}</select><span>{item.successMetric}</span></div>)}</div></div>;
}

function SettingsView({data,onRefresh}:{data:IntelligenceData;onRefresh:()=>void}){
  return <div className="route-page settings-page">
    <div className="route-heading"><div><h2>Sync & system health</h2><p>Google Sheets is canonical. The browser receives normalized records, never service-account credentials.</p></div><button className="primary-button" onClick={onRefresh}><RefreshCw size={16}/>Run refresh</button></div>
    <div className="settings-grid"><Health name="Canonical store" value="Google Sheets" status={data.meta.mode==="google-sheets"?"Connected":"Unavailable"}/><Health name="Dataset revision" value={String(data.meta.datasetRevision)} status={data.meta.lastSync||"Unknown"}/><Health name="Core records" value={String(data.meta.coreCount)} status={`${data.meta.sourceCount} sources`}/><Health name="Refresh polling" value="30 seconds" status="Revision-only polling"/></div>
    <section className="runbook"><h3>Operational checks</h3><ol><li>Dashboard writes locate the row by immutable ID and compare <code>row_version</code>.</li><li>Google Drive modification metadata detects direct Sheet edits without requiring an Apps Script trigger.</li><li>A changed revision reloads the complete bounded dataset; a connection failure displays an unavailable state.</li><li>Prices, reach, funding, revenue, and material features require a URL, observation date, and terminal evidence state.</li></ol></section>
    <section className="runbook intake"><h3>HireNudge internal evidence intake</h3><p>Final gap scores stay disabled until Priyansh and Baskaran supply aggregate, de-identified evidence. Current state: <strong>Not supplied</strong>.</p><div className="intake-grid">{["Product & modules","Pricing & unit costs","Funnels & cohorts","Support & interviews","Approved claims","Privacy & outreach","Roadmap & constraints"].map((item)=><div key={item}><Check size={16}/><span>{item}</span><em>Not supplied</em></div>)}</div><p className="method-note">Use the repository intake guide. Do not upload raw resumes, inbox contents, immigration documents or candidate-level personal data to the research Sheet.</p></section>
  </div>;
}
function Health({name,value,status}:{name:string;value:string;status:string}){return <article><Gauge size={21}/><span>{name}</span><strong>{value}</strong><small>{status}</small></article>}

function EditorModal({state,onClose,onSaved}:{state:NonNullable<ModalState>;onClose:()=>void;onSaved:(message:string)=>void}){
  const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [today]=useState(()=>new Date().toISOString().slice(0,10)); const isAction=state.type==="action";
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setError("");const values=Object.fromEntries(new FormData(event.currentTarget).entries());let url="/api/notes";let payload:Record<string,unknown>={platformId:state.platform.id,title:values.title,body:values.body};if(state.type==="source"){url="/api/sources";payload={platformId:state.platform.id,title:values.title,claim:values.claim,url:values.url,type:values.type,observedDate:values.observedDate,confidence:values.confidence};}if(isAction){url="/api/tracker";payload={id:`action-${crypto.randomUUID()}`,title:values.title,sourceId:state.opportunity?.sourceId||"",customerProblem:values.customerProblem,intendedOutcome:values.intendedOutcome,recommendationType:state.opportunity?.recommendation||"Test",actionType:values.actionType,owner:"Priyansh; Baskaran",coOwners:["Priyansh","Baskaran"],dueDate:values.dueDate,priority:values.priority,effort:"M",risk:state.opportunity?.privacyRisk||"Review",confidence:state.opportunity?.evidenceConfidence||"Medium",experiment:values.experiment,baseline:"Internal analytics baseline required",successMetric:values.successMetric,threshold:"Predefine before test",status:"Proposed",decision:"Pending",resultNotes:"",rowVersion:1,createdAt:"",updatedAt:"",origin:{entityType:state.opportunity?"recommendation":"platform",entityId:state.opportunity?.id||state.platform.id,snapshot:state.opportunity?.rationale||state.platform.name,sourceIds:state.opportunity?.sourceId?[state.opportunity.sourceId]:[]}};}try{const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Write failed");onSaved(isAction?"Action created in Google Sheets":state.type==="source"?"Draft source added to the evidence ledger":"Research note saved");}catch(error){setError(error instanceof Error?error.message:"Write failed");setSaving(false);}};
  // The due-date default is captured once above; this suppression only covers the legacy inline fallback retained in the compact JSX.
  // eslint-disable-next-line react-hooks/purity
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event)=>event.target===event.currentTarget&&onClose()}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header><div><span>{state.platform.name}</span><h2 id="modal-title">{state.type==="source"?"Add source":state.type==="note"?"Add research note":"Create linked action"}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={19}/></button></header><form onSubmit={submit}>{state.type==="source"?<><Field label="Source title" name="title" required defaultValue={`${state.platform.name} source`}/><Field label="Claim supported" name="claim" required/><Field label="URL" name="url" type="url" required defaultValue={state.platform.website}/><div className="form-grid"><SelectField label="Source type" name="type" values={["Official product","Official pricing","Official help","App store","Credible press","Review platform","User-provided research"]}/><Field label="Observed date" name="observedDate" type="date" required defaultValue={today}/></div><SelectField label="Confidence" name="confidence" values={["High","Medium","Low"]}/></>:state.type==="note"?<><Field label="Title" name="title" required defaultValue={`${state.platform.name} research note`}/><TextArea label="Research note" name="body" required/></>:<><Field label="Action" name="title" required defaultValue={state.opportunity?.name||`Research ${state.platform.name}`}/><SelectField label="Action type" name="actionType" values={["Add","Improve","Remove","Discuss","Research","Test","Partner","Watch","Defer"]}/><TextArea label="Customer problem" name="customerProblem" required defaultValue={state.opportunity?.rationale||"Clarify the customer problem and evidence before deciding."}/><Field label="Intended outcome" name="intendedOutcome" required defaultValue="Increase qualified interview rate per 10 high-fit applications"/><div className="form-grid"><Field label="Co-owners" name="owner" required defaultValue="Priyansh; Baskaran"/><Field label="Due date" name="dueDate" type="date" required defaultValue={new Date(Date.now()+14*86400000).toISOString().slice(0,10)}/></div><SelectField label="Priority" name="priority" values={["P0","P1","P2","P3"]}/><TextArea label="Smallest validation experiment" name="experiment" required defaultValue={`Run a bounded test with 5–10 active job seekers.`}/><Field label="Success metric" name="successMetric" required defaultValue="Qualified interview rate per 10 high-fit applications"/></>}{error?<p className="form-error"><CircleAlert size={16}/>{error}</p>:null}<footer><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving?"Saving…":"Save"}</button></footer></form></div></div>;
}
function Field({label,name,type="text",defaultValue,required=false}:{label:string;name:string;type?:string;defaultValue?:string;required?:boolean}){return <label className="form-field"><span>{label}</span><input name={name} type={type} defaultValue={defaultValue} required={required}/></label>}
function TextArea({label,name,defaultValue,required=false}:{label:string;name:string;defaultValue?:string;required?:boolean}){return <label className="form-field"><span>{label}</span><textarea name={name} defaultValue={defaultValue} required={required} rows={5}/></label>}
function SelectField({label,name,values}:{label:string;name:string;values:string[]}){return <label className="form-field"><span>{label}</span><select name={name}>{values.map((value)=><option key={value}>{value}</option>)}</select></label>}
function Mark({name,large=false}:{name:string;large?:boolean}){return <span className={`platform-mark ${large?"large":""}`}>{name.slice(0,1).toUpperCase()}</span>}
function terminalText(value?:string){if(!value)return "Not found after exhaustive search";if(/needs research|needs verification|manual verification required|research pending|unknown/i.test(value))return "Not found after exhaustive search";return value;}
function Fact({label,value,link}:{label:string;value?:string;link?:string}){const text=terminalText(value);return <div className="fact"><span>{label}</span>{link&&!/not found|not publicly disclosed/i.test(text)?<a href={link} target="_blank" rel="noreferrer">{text}<ExternalLink size={13}/></a>:<strong className={/not found|not publicly disclosed|not applicable/i.test(text)?"terminal":""}>{text}</strong>}</div>}
function EvidenceFact({label,value,claim,sourceById}:{label:string;value?:string;claim?:ClaimObservation;sourceById:Map<string,Source>}){return <div className="fact evidence-fact"><span>{label}</span><strong className={/not found|not publicly disclosed|not applicable/i.test(terminalText(value))?"terminal":""}>{terminalText(value)}</strong>{claim?<small>{claim.researchState} · {claim.confidence} · {claim.observedDate}</small>:null}<EvidenceLinks ids={claim?.sourceIds||[]} sourceById={sourceById}/></div>}
function EvidenceRichText({value,claim,sourceById}:{value?:string;claim?:ClaimObservation;sourceById:Map<string,Source>}){return <div className="evidence-rich"><p className={`rich-text ${/not found|not publicly disclosed|not applicable/i.test(terminalText(value))?"terminal":""}`}>{terminalText(value)}</p>{claim?<small>{claim.researchState} · {claim.confidence} confidence · observed {claim.observedDate}</small>:null}<EvidenceLinks ids={claim?.sourceIds||[]} sourceById={sourceById}/></div>}
function EvidenceLinks({ids,sourceById}:{ids:string[];sourceById:Map<string,Source>}){const linked=ids.map((id)=>sourceById.get(id)).filter(Boolean) as Source[];if(!linked.length)return null;return <div className="evidence-links">{linked.slice(0,4).map((source)=><a key={source.id} href={source.url} target="_blank" rel="noreferrer">Source <ExternalLink size={11}/></a>)}</div>}
function TerminalState({text}:{text:string}){return <div className="terminal-state"><CircleAlert size={17}/><span>{text}</span></div>}
function Empty({title,body}:{title:string;body:string}){return <div className="empty-state"><SlidersHorizontal size={25}/><strong>{title}</strong><p>{body}</p></div>}
function host(value:string){try{return new URL(value).hostname.replace(/^www\./,"")}catch{return ""}}
function UnavailableState({data,onRefresh}:{data:IntelligenceData;onRefresh:()=>void}){return <div className="unavailable"><CircleAlert size={34}/><h2>Live research is unavailable</h2><p>{data.meta.health}</p><button className="primary-button" onClick={onRefresh}><RefreshCw size={17}/>Retry connection</button></div>}
