import type { Priority } from "./types";

export interface FounderDecision {
  id: string;
  question: string;
  recommendation: string;
  alternatives: string[];
  evidence: string[];
  impactOfDelay: string;
  priority: Priority;
  dependency: string;
  deadline: string;
  status: "To Be Discussed" | "Approved" | "Deferred" | "Rejected";
  initiativeIds: string[];
}

export const founderDecisions: readonly FounderDecision[] = [
  { id: "FD-01", question: "What exact outcome and activation definition should HireNudge optimise?", recommendation: "One source-verified job, reviewed truthful packet and next action; track qualified interview responses per 10 reviewed applications.", alternatives: ["Use paid retention as an interim leading measure", "Use packet completion only during instrumentation calibration"], evidence: ["HN-002", "HN-011", "Analytics research"], impactOfDelay: "Analytics and roadmap choices remain ungrounded.", priority: "P0 — Must Have", dependency: "Event feasibility and self-reported outcome completeness", deadline: "Now", status: "To Be Discussed", initiativeIds: ["HN-002", "HN-011"] },
  { id: "FD-02", question: "Which provisional ICP and role families should guide the first 90 days?", recommendation: "Start with India-based employed switchers and select one or two role families from evidence.", alternatives: ["Start with students", "Start with one mobility corridor"], evidence: ["HN-019", "GTM evaluation"], impactOfDelay: "Product and acquisition work remain too broad.", priority: "P1 — Important", dependency: "Current-user, job-coverage and paid-behavior evidence", deadline: "Founder to set", status: "To Be Discussed", initiativeIds: ["HN-019"] },
  { id: "FD-03", question: "Will HireNudge reject fully autonomous and high-volume external actions?", recommendation: "Require human review and quality caps for every application and message.", alternatives: ["Permit narrowly bounded automation after a separate platform and quality review"], evidence: ["HN-026", "Gmail and outreach research"], impactOfDelay: "Claims, controls and platform risk remain inconsistent.", priority: "P0 — Must Have", dependency: "Current product behavior and platform terms", deadline: "Now", status: "To Be Discussed", initiativeIds: ["HN-026", "HN-012"] },
  { id: "FD-04", question: "What substantiation standard should apply to material public claims?", recommendation: "Require a source, method, permission, owner and review date.", alternatives: ["Remove all outcome claims until internal evidence exists"], evidence: ["HN-001", "Public homepage and pricing audit"], impactOfDelay: "Trust, legal and refund exposure continues.", priority: "P0 — Must Have", dependency: "Claim inventory and permissions", deadline: "Now", status: "To Be Discussed", initiativeIds: ["HN-001"] },
  { id: "FD-05", question: "Who has immediate authority to remove exposed sensitive data and close the incident?", recommendation: "Remove the identifiers, scan all public outputs and document incident closure immediately.", alternatives: ["There is no credible reason to defer containment"], evidence: ["HN-010A", "Public portfolio observation"], impactOfDelay: "Critical privacy exposure may persist.", priority: "P0 — Must Have", dependency: "Site access and incident assessment", deadline: "Immediate", status: "To Be Discussed", initiativeIds: ["HN-010A"] },
  { id: "FD-06", question: "Should the application packet become HireNudge’s core product object?", recommendation: "Use a job-centered packet backed by candidate evidence.", alternatives: ["Keep the current module-first suite", "Use the tracker as the primary object"], evidence: ["HN-004A", "HN-004B", "Competitor workflow observations"], impactOfDelay: "Modules remain disconnected and version/outcome work lacks a shared model.", priority: "P1 — Important", dependency: "Prototype and domain-model review", deadline: "Founder to set", status: "To Be Discussed", initiativeIds: ["HN-004A", "HN-004B"] },
  { id: "FD-07", question: "How should HireNudge describe job fit and numeric scores?", recommendation: "Use profile-to-role alignment with requirements, evidence, gaps and unknowns; never imply hiring probability.", alternatives: ["Keep a secondary number after validation", "Remove the aggregate number entirely"], evidence: ["HN-005", "NIST AI RMF", "Matcher screenshots"], impactOfDelay: "False precision remains central to the experience.", priority: "P0 — Must Have", dependency: "Extraction and evaluation results", deadline: "Now", status: "To Be Discussed", initiativeIds: ["HN-005"] },
  { id: "FD-08", question: "What job-source rights and quality policy should govern discovery?", recommendation: "Use curated public ATS boards and licensed partners; do not make restricted scraping the core.", alternatives: ["Use a single licensed aggregator", "Limit discovery to direct employer partnerships"], evidence: ["HN-006A", "HN-006B", "Official ATS and provider sources"], impactOfDelay: "Rights, freshness and coverage engineering cannot be scoped safely.", priority: "P0 — Must Have", dependency: "Current source inventory, contracts and 500-job audit", deadline: "Founder to set", status: "To Be Discussed", initiativeIds: ["HN-006A", "HN-006B"] },
  { id: "FD-09", question: "Will the initial Gmail boundary be send-only with no inbox read?", recommendation: "Request `gmail.send` only when the user sends; review every message and support revoke/delete.", alternatives: ["Offer copy or mailto without OAuth", "Add broader scopes only after a separate need and security review"], evidence: ["HN-012", "Official Google OAuth documentation"], impactOfDelay: "OAuth, security and onboarding design remain blocked.", priority: "P0 — Must Have", dependency: "Current scopes, token architecture and Google verification", deadline: "Now", status: "To Be Discussed", initiativeIds: ["HN-012"] },
  { id: "FD-10", question: "Which contact provider, jurisdiction and recipient use case may enter a governed pilot?", recommendation: "Choose one provider, one country and one high-intent recipient use case after legal review.", alternatives: ["Defer contact discovery", "Use user-supplied recipients only"], evidence: ["HN-013", "Provider and regulator research"], impactOfDelay: "Vendor and outreach scope remain open-ended.", priority: "P1 — Important", dependency: "DPA, lawful basis, notice and suppression", deadline: "Before build", status: "To Be Discussed", initiativeIds: ["HN-013"] },
  { id: "FD-11", question: "Should the commercial proof target be 50 or 100 paying customers, and what capacity is available?", recommendation: "Use four cohorts of 25; the first 10 eligible users calibrate cohort 1.", alternatives: ["Retain the earlier first-50 threshold", "Run a smaller paid role-family cohort before committing to 100"], evidence: ["HN-018", "First-50 strategy", "First-100 evaluation"], impactOfDelay: "Two conflicting acquisition plans remain in circulation.", priority: "P1 — Important", dependency: "Team capacity, COGS and pricing interviews", deadline: "Founder to set", status: "To Be Discussed", initiativeIds: ["HN-018", "HN-017"] },
  { id: "FD-12", question: "What product and brand promise should HireNudge test?", recommendation: "Lead with truthful, higher-quality applications and clear next steps.", alternatives: ["Continue broad all-in-one positioning", "Lead with India-to-global mobility after validation"], evidence: ["Brand-language evaluation", "HN-001", "HN-004B"], impactOfDelay: "Product, landing and campaign language will diverge.", priority: "P1 — Important", dependency: "Claim inventory and message tests", deadline: "Founder to set", status: "To Be Discussed", initiativeIds: ["HN-001", "HN-004B"] },
  { id: "FD-13", question: "What TerraTern and HireNudge controller, purpose and consent boundary should apply?", recommendation: "Separate purpose and access; require explicit opt-in for every cross-use.", alternatives: ["Keep brands completely separate", "Use a narrowly defined joint journey after legal review"], evidence: ["HN-027", "DPDP sources", "Repository operating context"], impactOfDelay: "A critical privacy and brand dependency remains unresolved.", priority: "P0 — Must Have", dependency: "Current data map and counsel", deadline: "Now", status: "To Be Discussed", initiativeIds: ["HN-027"] },
  { id: "FD-14", question: "Should interview preparation launch transcript-first before realtime voice?", recommendation: "Validate transcript coaching first and prohibit personality, emotion, honesty, accent and employability scores.", alternatives: ["Launch a limited opt-in voice prototype after privacy and accent evaluation"], evidence: ["HN-014", "HN-015", "NIST, EEOC and WCAG"], impactOfDelay: "The team may build the highest-cost and highest-risk layer first.", priority: "P1 — Important", dependency: "Human benchmark, privacy and accessibility design", deadline: "Founder to set", status: "To Be Discussed", initiativeIds: ["HN-014", "HN-015"] },
  { id: "FD-15", question: "Who owns analytics, job data, claims, trust and the research cadence?", recommendation: "Assign one accountable owner to each control and weekly decision loop.", alternatives: ["Use temporary founder ownership with explicit expiry dates"], evidence: ["HN-023", "HN-028B", "Research validation"], impactOfDelay: "P0 work has no accountable owner or deadline.", priority: "P0 — Must Have", dependency: "Team capacity and role confirmation", deadline: "Now", status: "To Be Discussed", initiativeIds: ["HN-002", "HN-006A", "HN-023", "HN-028B"] },
];

