export interface PresentationChapter {
  number: number;
  title: string;
  eyebrow: string;
  thesis: string;
  bullets: string[];
  initiativeIds?: string[];
}

export const presentationChapters: readonly PresentationChapter[] = [
  { number: 1, title: "Where HireNudge is today", eyebrow: "Current state", thesis: "HireNudge shows broad candidate-workflow coverage; the supplied evidence does not establish a coherent or retained operating system.", bullets: ["Onboarding, documents, matching, outreach, tracking, interview preparation and autofill are visible.", "Live depth, customer outcomes and product-market fit require internal evidence.", "Breadth is an asset only when one application journey becomes clear."], initiativeIds: ["HN-002", "HN-004A"] },
  { number: 2, title: "What was evaluated", eyebrow: "Evidence scope", thesis: "The review combined repository evidence, public HireNudge surfaces, supplied screenshots, competitors, ads, APIs, policies and regulation.", bullets: ["28 HireNudge and 116 competitor product screenshots.", "296 competitor ad assets, reviewed as creative evidence without performance data.", "18 core research reports and 38 canonical initiatives."] },
  { number: 3, title: "Strongest findings", eyebrow: "Research synthesis", thesis: "The central gap is connected, measurable trust rather than feature count.", bullets: ["The product is module-first while the user’s task is job-first.", "Scores, jobs and AI edits need visible evidence and uncertainty.", "Activation, retention and outcome data were not supplied."], initiativeIds: ["HN-004B", "HN-005", "HN-008"] },
  { number: 4, title: "What is already in progress", eyebrow: "Team discussion", thesis: "The team is exploring a broad redesign, Nudge Studio, matching, job data, voice, outreach, lifecycle and content work.", bullets: ["Competitor ad collection and content research are described as in progress.", "Discussion does not mean approval, feasibility or delivery.", "The dashboard keeps evidence, priority and decision status separate."], initiativeIds: ["HN-022A"] },
  { number: 5, title: "Product improvements", eyebrow: "Core loop", thesis: "Protect trust and make one application coherent before adding another standalone generator.", bullets: ["Lead with explainable alignment and job provenance.", "Preserve candidate truth and document versions.", "Connect the minimum tracker and outcome loop."], initiativeIds: ["HN-005", "HN-006B", "HN-008", "HN-011"] },
  { number: 6, title: "New feature opportunities", eyebrow: "Product system", thesis: "Candidate evidence plus a live job plus an application packet can connect the entire journey.", bullets: ["Candidate evidence profile and application packet.", "Search-status mode and source-aware job cards.", "Transcript-first, job-and-round interview practice."], initiativeIds: ["HN-003", "HN-004B", "HN-014", "HN-032"] },
  { number: 7, title: "UI/UX direction", eyebrow: "Experience", thesis: "Move from a module menu to a job-centered next-action system, then apply the modern visual layer.", bullets: ["Import evidence → choose role → review alignment → improve packet → set next action.", "Ask for Gmail, authorization and audio only at the relevant moment.", "Defer mascot and motion work until comprehension and activation are proven."], initiativeIds: ["HN-004A", "HN-021", "HN-030"] },
  { number: 8, title: "Brand-language direction", eyebrow: "Positioning", thesis: "Promise inspectable behavior, not automated certainty.", bullets: ["Working position: an India-first job-search operating system for higher-quality applications.", "Use profile-to-role alignment, source-backed and reviewed.", "Remove or substantiate autopilot, bulk, perfect, guaranteed and outcome claims."], initiativeIds: ["HN-001", "HN-005", "HN-026"] },
  { number: 9, title: "Social strategy", eyebrow: "Learning engine", thesis: "Use original founder and product content to learn before paid acquisition scales.", bullets: ["LinkedIn for authority and teardowns; Instagram for visual education; X for fast research notes.", "One problem, one proof object and one CTA per creative.", "Paid scale waits for activation, repeat use, claims and margin gates."], initiativeIds: ["HN-022A", "HN-022B"] },
  { number: 10, title: "GTM strategy", eyebrow: "Initial wedge", thesis: "Start India-to-India with an urgent employed-switcher hypothesis and select role families from evidence.", bullets: ["Provisional ICP: English-speaking employed professionals switching in 30–60 days.", "Begin with direct networks, communities, clinics and disclosed partners.", "Treat remote and mobility as bounded constraints, not universal corridors."], initiativeIds: ["HN-019", "HN-020"] },
  { number: 11, title: "First 100 customers", eyebrow: "Commercial proof", thesis: "Recruit paying learners, not registrations.", bullets: ["Four cohorts of 25; the first 10 eligible users calibrate cohort 1.", "Offer a bounded Application Quality Sprint tied to real roles.", "Review behavior, support burden, willingness to pay and outcomes before each next cohort."], initiativeIds: ["HN-017", "HN-018"] },
  { number: 12, title: "Retention", eyebrow: "Useful return", thesis: "Bring the user back for the next useful action, not a generic content broadcast.", bullets: ["Tie reminders to jobs, packets, follow-ups and interview dates.", "Let users control categories, frequency, quiet mode and search status.", "Measure incremental action and retention with complaint guardrails."], initiativeIds: ["HN-016", "HN-032"] },
  { number: 13, title: "Now, Next and Later", eyebrow: "Sequence", thesis: "Protect and prove before expanding.", bullets: ["Now: claims, data, alignment, truth, tracker and external-action controls.", "Next: evidence, packet, versions, practice, lifecycle and operating loop.", "Later: voice, mobility, portfolio, referrals, B2B and brand motion."], initiativeIds: ["HN-002", "HN-004B", "HN-015", "HN-020"] },
  { number: 14, title: "Risks", eyebrow: "Dependencies", thesis: "Internal evidence, claims, job rights, Gmail, consent and security gate execution.", bullets: ["Sensitive-data remediation and claim proof cannot wait for a redesign.", "Job and outreach scope are blocked by rights, security and legal confirmation.", "No P0 initiative currently has an assigned owner."], initiativeIds: ["HN-010A", "HN-006A", "HN-012", "HN-027", "HN-028B"] },
  { number: 15, title: "Founder decisions", eyebrow: "Meeting close", thesis: "Decide the boundaries that unblock evidence and execution.", bullets: ["Outcome, ICP, autonomy, claims, packet and alignment language.", "Job-source, Gmail, contact and TerraTern boundaries.", "First-customer target, interview sequence and accountable owners."], initiativeIds: ["HN-001", "HN-002", "HN-019", "HN-026"] },
];
