import React, { type ReactNode } from "react";
import { ArrowRight, Check, CircleAlert } from "lucide-react";
import { PriorityBadge, StatusBadge } from "../primitives";
import type { Initiative } from "../types";
import styles from "../strategy.module.css";

export function MetricStrip({ items }: { items: readonly { value: string | number; label: string; note?: string }[] }) { return <div className={styles.metricStrip}>{items.map((item) => <div key={item.label}><strong>{item.value}</strong><span>{item.label}</span>{item.note ? <small>{item.note}</small> : null}</div>)}</div>; }
export function EditorialGrid({ children, columns = 3 }: { children: ReactNode; columns?: 2 | 3 | 4 }) { return <div className={`${styles.editorialGrid} ${styles[`columns${columns}`]}`}>{children}</div>; }
export function EditorialItem({ index, title, children, aside }: { index?: string; title: string; children: ReactNode; aside?: ReactNode }) { return <article className={styles.editorialItem}>{index ? <span className={styles.itemIndex}>{index}</span> : null}<h3>{title}</h3><div className={styles.itemBody}>{children}</div>{aside ? <div className={styles.itemAside}>{aside}</div> : null}</article>; }
export function NumberedList({ items }: { items: readonly string[] }) { return <ol className={styles.numberedList}>{items.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2,"0")}</span><p>{item}</p></li>)}</ol>; }
export function BulletList({ items, alert = false }: { items: readonly string[]; alert?: boolean }) { const Icon = alert ? CircleAlert : Check; return <ul className={styles.bulletList}>{items.map((item) => <li key={item}><Icon aria-hidden="true" size={15} /><span>{item}</span></li>)}</ul>; }
export function Flow({ items }: { items: readonly { title?: string; stage?: string; detail: string }[] }) { return <ol className={styles.flow}>{items.map((item, index) => <li key={item.title ?? item.stage}><span>{String(index + 1).padStart(2,"0")}</span><div><strong>{item.title ?? item.stage}</strong><p>{item.detail}</p></div>{index < items.length - 1 ? <ArrowRight aria-hidden="true" /> : null}</li>)}</ol>; }
export function InitiativePreview({ item }: { item: Initiative }) { return <article className={styles.priorityPreview}><span>{item.id} · {item.workstream}</span><h3>{item.title}</h3><p>{item.recommendation}</p><div><PriorityBadge value={item.ai_suggested_priority} /><StatusBadge kind="decision" value={item.decision_status} /><StatusBadge kind="horizon" value={item.roadmap_horizon} /></div></article>; }
export function ComparisonTable({ rows, labels = ["Current", "Risk / principle", "Recommended"] }: { rows: readonly Record<string,string>[]; labels?: readonly [string,string,string] }) { const keys = Object.keys(rows[0] ?? {}); return <div className={styles.comparison} role="table" aria-label="Current and recommended comparison"><div className={styles.comparisonHead} role="row">{labels.map((label) => <span role="columnheader" key={label}>{label}</span>)}</div>{rows.map((row,index) => <div className={styles.comparisonRow} role="row" key={index}>{keys.slice(0,3).map((key) => <span role="cell" key={key}>{row[key]}</span>)}</div>)}</div>; }
export function Pillar({ label, value, tone }: { label: string; value: string; tone?: "accent" | "dark" }) { return <div className={`${styles.pillar} ${tone === "dark" ? styles.pillarDark : tone === "accent" ? styles.pillarAccent : ""}`}><span>{label}</span><strong>{value}</strong></div>; }
